language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - npm run lint
 - npm run test-ci

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
